# Generated by Django 3.2.5 on 2021-07-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='transactions',
        ),
    ]
