# Generated by Django 3.2.5 on 2021-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repeat_until',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
