# Generated by Django 3.2.5 on 2021-07-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210727_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repeat_until',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
