# Generated by Django 3.2.5 on 2021-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_repeat_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='skipped_months',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_day',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
