# Generated by Django 3.2.5 on 2021-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(max_length=20)),
                ('balance', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
